package com.hjq.demo.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hjq.demo.daerxiansheng.sql.FrendsEntity;
import com.hjq.demo.daerxiansheng.sql.FrendsMessageEntity;
import com.hjq.demo.daerxiansheng.sql.GroupEntity;
import com.hjq.demo.daerxiansheng.sql.GroupMessageEntity;
import com.hjq.demo.daerxiansheng.sql.GroupUserEntity;
import com.hjq.demo.daerxiansheng.sql.MessageListEntity;
import com.hjq.demo.daerxiansheng.sql.TokenEntity;
import com.hjq.demo.daerxiansheng.sql.VirtualAppEntity;

import com.hjq.demo.greenDao.FrendsEntityDao;
import com.hjq.demo.greenDao.FrendsMessageEntityDao;
import com.hjq.demo.greenDao.GroupEntityDao;
import com.hjq.demo.greenDao.GroupMessageEntityDao;
import com.hjq.demo.greenDao.GroupUserEntityDao;
import com.hjq.demo.greenDao.MessageListEntityDao;
import com.hjq.demo.greenDao.TokenEntityDao;
import com.hjq.demo.greenDao.VirtualAppEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig frendsEntityDaoConfig;
    private final DaoConfig frendsMessageEntityDaoConfig;
    private final DaoConfig groupEntityDaoConfig;
    private final DaoConfig groupMessageEntityDaoConfig;
    private final DaoConfig groupUserEntityDaoConfig;
    private final DaoConfig messageListEntityDaoConfig;
    private final DaoConfig tokenEntityDaoConfig;
    private final DaoConfig virtualAppEntityDaoConfig;

    private final FrendsEntityDao frendsEntityDao;
    private final FrendsMessageEntityDao frendsMessageEntityDao;
    private final GroupEntityDao groupEntityDao;
    private final GroupMessageEntityDao groupMessageEntityDao;
    private final GroupUserEntityDao groupUserEntityDao;
    private final MessageListEntityDao messageListEntityDao;
    private final TokenEntityDao tokenEntityDao;
    private final VirtualAppEntityDao virtualAppEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        frendsEntityDaoConfig = daoConfigMap.get(FrendsEntityDao.class).clone();
        frendsEntityDaoConfig.initIdentityScope(type);

        frendsMessageEntityDaoConfig = daoConfigMap.get(FrendsMessageEntityDao.class).clone();
        frendsMessageEntityDaoConfig.initIdentityScope(type);

        groupEntityDaoConfig = daoConfigMap.get(GroupEntityDao.class).clone();
        groupEntityDaoConfig.initIdentityScope(type);

        groupMessageEntityDaoConfig = daoConfigMap.get(GroupMessageEntityDao.class).clone();
        groupMessageEntityDaoConfig.initIdentityScope(type);

        groupUserEntityDaoConfig = daoConfigMap.get(GroupUserEntityDao.class).clone();
        groupUserEntityDaoConfig.initIdentityScope(type);

        messageListEntityDaoConfig = daoConfigMap.get(MessageListEntityDao.class).clone();
        messageListEntityDaoConfig.initIdentityScope(type);

        tokenEntityDaoConfig = daoConfigMap.get(TokenEntityDao.class).clone();
        tokenEntityDaoConfig.initIdentityScope(type);

        virtualAppEntityDaoConfig = daoConfigMap.get(VirtualAppEntityDao.class).clone();
        virtualAppEntityDaoConfig.initIdentityScope(type);

        frendsEntityDao = new FrendsEntityDao(frendsEntityDaoConfig, this);
        frendsMessageEntityDao = new FrendsMessageEntityDao(frendsMessageEntityDaoConfig, this);
        groupEntityDao = new GroupEntityDao(groupEntityDaoConfig, this);
        groupMessageEntityDao = new GroupMessageEntityDao(groupMessageEntityDaoConfig, this);
        groupUserEntityDao = new GroupUserEntityDao(groupUserEntityDaoConfig, this);
        messageListEntityDao = new MessageListEntityDao(messageListEntityDaoConfig, this);
        tokenEntityDao = new TokenEntityDao(tokenEntityDaoConfig, this);
        virtualAppEntityDao = new VirtualAppEntityDao(virtualAppEntityDaoConfig, this);

        registerDao(FrendsEntity.class, frendsEntityDao);
        registerDao(FrendsMessageEntity.class, frendsMessageEntityDao);
        registerDao(GroupEntity.class, groupEntityDao);
        registerDao(GroupMessageEntity.class, groupMessageEntityDao);
        registerDao(GroupUserEntity.class, groupUserEntityDao);
        registerDao(MessageListEntity.class, messageListEntityDao);
        registerDao(TokenEntity.class, tokenEntityDao);
        registerDao(VirtualAppEntity.class, virtualAppEntityDao);
    }
    
    public void clear() {
        frendsEntityDaoConfig.clearIdentityScope();
        frendsMessageEntityDaoConfig.clearIdentityScope();
        groupEntityDaoConfig.clearIdentityScope();
        groupMessageEntityDaoConfig.clearIdentityScope();
        groupUserEntityDaoConfig.clearIdentityScope();
        messageListEntityDaoConfig.clearIdentityScope();
        tokenEntityDaoConfig.clearIdentityScope();
        virtualAppEntityDaoConfig.clearIdentityScope();
    }

    public FrendsEntityDao getFrendsEntityDao() {
        return frendsEntityDao;
    }

    public FrendsMessageEntityDao getFrendsMessageEntityDao() {
        return frendsMessageEntityDao;
    }

    public GroupEntityDao getGroupEntityDao() {
        return groupEntityDao;
    }

    public GroupMessageEntityDao getGroupMessageEntityDao() {
        return groupMessageEntityDao;
    }

    public GroupUserEntityDao getGroupUserEntityDao() {
        return groupUserEntityDao;
    }

    public MessageListEntityDao getMessageListEntityDao() {
        return messageListEntityDao;
    }

    public TokenEntityDao getTokenEntityDao() {
        return tokenEntityDao;
    }

    public VirtualAppEntityDao getVirtualAppEntityDao() {
        return virtualAppEntityDao;
    }

}
